### ISSUE TITLE
General Availability

### ISSUE THREAD

**Issue by PSanetra** [Azure/azure-schema-registry-for-kafka#16]
Is there some ETA when the schema registry will get out of preview and becomes GA?

**Comment by stevenylai** [comment]
Yes would be better for this to be part of Azure SDK BOM

**Comment by PSanetra** [comment]
I will close this issue as the schema is GA now

**Comment by stevenylai** [comment]
Schema registry yes: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/schemaregistry but I thought this one is more about the registry's integration with Kafka client? Anyway, I will check if there is any plan to move this one to Azure SDK too
