### ISSUE TITLE
Registration failure error doesn't provide a meaningful error message

### ISSUE THREAD

**Issue by sjkwak** [Azure/azure-schema-registry-for-kafka#4]
In case a client application doesn't have a permission to register, an error thrown by the SR client module doesn't provide a meaningful error message. Here is an error message.

_[main] ERROR com.azure.data.schemaregistry.client.CachedSchemaRegistryClient - Register operation failed, unexpected service response.
[main] ERROR com.azure.data.schemaregistry.AbstractDataSerializer - Error registering Avro schema. Group: my-schema-group, name: com.azure.schemaregistry.samples.AvroUser
Exception in thread "main" org.apache.kafka.common.errors.SerializationException: com.azure.data.schemaregistry.client.SchemaRegistryClientException: Register operation failed, unexpected service response._

**Comment by arerlend** [comment]
Fixed for 1.0.0-beta.4
